language: scala

scala:
  - 2.11.12
  - 2.12.8
  - 2.13.1
jdk:
  - openjdk8
  - openjdk11

install:
  - rvm use 2.6.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.8.5

script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport
  # Test documentation
  - sbt ++$TRAVIS_SCALA_VERSION makeMicrosite

after_success:
  - bash <(curl -s https://codecov.io/bash)

# cache stuff, hopefully shortening build times
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
